moderepo/bizstack-console-plugin-samples

component_plugin_template_my_account/package-lock.json, component_plugin_template_my_account/package.json, component_plugin_template_my_account/src/my-account-components/MyAccountInfoComponent.tsx, component_plugin_template_my_account/src/my-account-components/config.ts, widget_plugin_template_weather_widget/package-lock.json, widget_plugin_template_weather_widget/package.json, widget_plugin_template_weather_widget/src/weather-widget/config.ts
=> install the latest bizconsole sdk

README.md
This PR adds some notes to the README.
=> Update README for alpha release

widget_plugin_template_weather_widget/package-lock.json, widget_plugin_template_weather_widget/package.json, widget_plugin_template_weather_widget/src/weather-widget/HumidityWidget.tsx, widget_plugin_template_weather_widget/src/weather-widget/TemperatureWidget.tsx, widget_plugin_template_weather_widget/src/weather-widget/utils.ts
Since we added a way for widgets to use the data request system even when it fetches its' own data, we can update the Weather widgets to use this new feature.
This PR is related to this PR https://github.com/moderepo/bizstack-console/pull/222
=> integrate weather widget with the dashboard's data request system

README.md
=> Component plugin documentation

.eslintrc.cjs, component_plugin_template_my_account/.eslintrc.cjs, component_plugin_template_my_account/package-lock.json, component_plugin_template_my_account/package.json, component_plugin_template_my_account/src/my-account-components/MyAccountPrefComponent.tsx, component_plugin_template_my_account/tsconfig.json, widget_plugin_template_weather_widget/package-lock.json, widget_plugin_template_weather_widget/package.json, widget_plugin_template_weather_widget/tsconfig.json
The SDK has some new changes so we need to update the plugin demo. One of the breaking changes is the changes to the Languages support.
NOTE: There are a lot of changes to the package_lock.json files because I updated my npm and node version.
=> update plugin samples

component_plugin_template_my_account/package-lock.json, component_plugin_template_my_account/package.json, component_plugin_template_my_account/src/my-account-components/config.ts, widget_plugin_template_weather_widget/package-lock.json, widget_plugin_template_weather_widget/package.json, widget_plugin_template_weather_widget/src/weather-widgets/config.ts
=> install the latest SDK

widget_plugin_template_weather_widget/vite.config.ts
The directory name is `weather-widgets` not `weather-widget`, missing the `s`.
=> fix directory name

README.md, component_plugin_template_my_account/package-lock.json, component_plugin_template_my_account/package.json, component_plugin_template_my_account/src/my-account-components/config.ts, widget_plugin_template_weather_widget/package-lock.json, widget_plugin_template_weather_widget/package.json, widget_plugin_template_weather_widget/src/weather-widgets/config.ts
- Bump SDK version
- add link to Developer Manual
- Spell out product name correctly
=> Updates for SDK 1.0.0

component_plugin_template_my_account/package-lock.json, component_plugin_template_my_account/package.json, component_plugin_template_my_account/src/my-account-components/CustomMapComponent.tsx, component_plugin_template_my_account/src/my-account-components/MyCustomAccountPage.tsx, component_plugin_template_my_account/src/my-account-components/config.ts, component_plugin_template_my_account/src/my-account-components/index.ts, component_plugin_template_my_account/tsconfig.json, component_plugin_template_my_account/vite.config.ts
This adds a sample to implement a custom map UI with Google Maps.
=> add custom map component sample

component_plugin_template_my_account/package-lock.json, component_plugin_template_my_account/package.json, component_plugin_template_my_account/src/my-account-components/CustomMapComponent.tsx, widget_plugin_template_weather_widget/package-lock.json, widget_plugin_template_weather_widget/package.json
https://console.bizstack.cloud/documentation/developer-manual/sdk_release_notes#v101
=> bump SDK from 1.0.0 to 1.0.1

component_plugin_template_my_account/package-lock.json, component_plugin_template_my_account/package.json, component_plugin_template_my_account/src/my-account-components/config.ts, widget_plugin_template_weather_widget/package-lock.json, widget_plugin_template_weather_widget/package.json, widget_plugin_template_weather_widget/src/weather-widgets/config.ts
https://console.bizstack.cloud/documentation/developer-manual/sdk_release_notes#v102
=>  bump SDK from 1.0.1 to 1.0.2

README.md, component_plugin_template_my_account/package-lock.json, component_plugin_template_my_account/package.json, sdk_demo/README.md, sdk_demo/SDKDemoPage.tsx, widget_plugin_template_weather_widget/package-lock.json, widget_plugin_template_weather_widget/package.json
- bump SDK to 1.1.0
- Added caution about the MUI version
- Added SDK demo page source code
=> bump SDK from 1.0.2 to 1.1.0

component_plugin_template_my_account/package-lock.json, component_plugin_template_my_account/package.json, component_plugin_template_my_account/src/my-account-components/config.ts, widget_plugin_template_weather_widget/package-lock.json, widget_plugin_template_weather_widget/package.json, widget_plugin_template_weather_widget/src/weather-widgets/config.ts
This should be merged after the production release on 17th Dec. 2024.
=> bump SDK from 1.4.1 to 1.5.0

component_plugin_template_my_account/src/my-account-components/MyAccountPrefComponent.tsx
=> fix compiler error

component_plugin_template_my_account/package-lock.json, component_plugin_template_my_account/package.json, component_plugin_template_my_account/src/my-account-components/config.ts, widget_plugin_template_weather_widget/package-lock.json, widget_plugin_template_weather_widget/package.json, widget_plugin_template_weather_widget/src/weather-widgets/config.ts
This will be released on January 21st, 2025.
=> bump SDK from 1.7.0 to 1.8.0

bizstack_console_sample_widgets/package-lock.json, bizstack_console_sample_widgets/package.json, bizstack_console_sample_widgets/src/widgets/config.ts, component_plugin_template_my_account/package-lock.json, component_plugin_template_my_account/package.json, component_plugin_template_my_account/src/my-account-components/config.ts, widget_plugin_template_weather_widget/package-lock.json, widget_plugin_template_weather_widget/package.json, widget_plugin_template_weather_widget/src/weather-widgets/config.ts
Production release date: 2025-02-04 PST
=> bump SDK from 1.8.0 to 1.9.0

bizstack_console_sample_widgets/package-lock.json, bizstack_console_sample_widgets/package.json, bizstack_console_sample_widgets/src/widgets/config.ts, component_plugin_template_my_account/package-lock.json, component_plugin_template_my_account/package.json, component_plugin_template_my_account/src/my-account-components/config.ts, widget_plugin_template_weather_widget/package-lock.json, widget_plugin_template_weather_widget/package.json, widget_plugin_template_weather_widget/src/weather-widgets/config.ts
Production release date: 2025-02-11 PST
=> bump SDK from 1.9.0 to 1.10.0

bizstack_console_sample_widgets/package-lock.json, bizstack_console_sample_widgets/package.json, bizstack_console_sample_widgets/src/widgets/config.ts, component_plugin_template_my_account/package-lock.json, component_plugin_template_my_account/package.json, component_plugin_template_my_account/src/my-account-components/config.ts, widget_plugin_template_weather_widget/package-lock.json, widget_plugin_template_weather_widget/package.json, widget_plugin_template_weather_widget/src/weather-widgets/config.ts
Production release date: 2025-02-18 PST
=> bump SDK from 1.10.0 to 1.11.0

bizstack_console_sample_widgets/package-lock.json, bizstack_console_sample_widgets/package.json, bizstack_console_sample_widgets/src/widgets/config.ts, component_plugin_template_my_account/package-lock.json, component_plugin_template_my_account/package.json, component_plugin_template_my_account/src/my-account-components/config.ts, widget_plugin_template_weather_widget/package-lock.json, widget_plugin_template_weather_widget/package.json, widget_plugin_template_weather_widget/src/weather-widgets/config.ts
Production release date: 2025-03-25 PST
=> bump SDK from 1.11.0 to 1.12.0

bizstack_console_sample_widgets/package-lock.json, bizstack_console_sample_widgets/package.json, bizstack_console_sample_widgets/src/widgets/config.ts, bizstack_console_sample_widgets/vite.config.ts, component_plugin_template_my_account/package-lock.json, component_plugin_template_my_account/package.json, component_plugin_template_my_account/src/my-account-components/config.ts, component_plugin_template_my_account/vite.config.ts, widget_plugin_template_weather_widget/package-lock.json, widget_plugin_template_weather_widget/package.json, widget_plugin_template_weather_widget/src/weather-widgets/config.ts, widget_plugin_template_weather_widget/vite.config.ts
Production release date: 2025-04-01 PST
=> bump SDK from 1.12.0 to 1.13.0

bizstack_console_sample_widgets/package-lock.json, bizstack_console_sample_widgets/package.json, bizstack_console_sample_widgets/src/widgets/config.ts, component_plugin_template_my_account/package-lock.json, component_plugin_template_my_account/package.json, component_plugin_template_my_account/src/my-account-components/config.ts, widget_plugin_template_weather_widget/package-lock.json, widget_plugin_template_weather_widget/package.json, widget_plugin_template_weather_widget/src/weather-widgets/config.ts
- Bump SDK from 1.13.0 to 1.14.0.
- Add pluginVersion to config.ts.
- Load bizConsoleVersion from @moderepo/bizstack-console-sdk/package.json.
=> bump SDK from 1.13.0 to 1.14.0, add pluginVersion, set bizConsoleVersion from package.json

bizstack_console_sample_widgets/package-lock.json, bizstack_console_sample_widgets/package.json, component_plugin_template_my_account/package-lock.json, component_plugin_template_my_account/package.json, widget_plugin_template_weather_widget/package-lock.json, widget_plugin_template_weather_widget/package.json
=> update SDK for sample plugins

bizstack_console_sample_widgets/package-lock.json, bizstack_console_sample_widgets/package.json, component_plugin_template_my_account/package-lock.json, component_plugin_template_my_account/package.json, widget_plugin_template_weather_widget/package-lock.json, widget_plugin_template_weather_widget/package.json
=> update to SDK 1.19.1

bizstack_console_sample_widgets/package-lock.json, bizstack_console_sample_widgets/package.json, bizstack_console_sample_widgets/src/widgets/gauge-widget/schema.ts, bizstack_console_sample_widgets/src/widgets/xy-chart-widget/schema.ts, component_plugin_template_my_account/package-lock.json, component_plugin_template_my_account/package.json, widget_plugin_template_weather_widget/package-lock.json, widget_plugin_template_weather_widget/package.json, widget_plugin_template_weather_widget/src/weather-widgets/sample-metric-data-widget/schema.ts, widget_plugin_template_weather_widget/src/weather-widgets/schema.ts
I have also updated the widgets implemented by these plugins to enable `Custom Time Control`
=> install the latest SDK for sample plugins

bizstack_console_sample_widgets/package-lock.json, bizstack_console_sample_widgets/package.json, component_plugin_template_my_account/package-lock.json, component_plugin_template_my_account/package.json, widget_plugin_template_weather_widget/package-lock.json, widget_plugin_template_weather_widget/package.json
=> install the lastest SDK

bizstack_console_sample_widgets/package-lock.json, bizstack_console_sample_widgets/package.json, component_plugin_template_my_account/package-lock.json, component_plugin_template_my_account/package.json, widget_plugin_template_weather_widget/package-lock.json, widget_plugin_template_weather_widget/package.json
=> update sample plugins' SDK
